paths["cactus"] := "
(LTrim Join`r`n
" nm_Walk(8, BackKey) "
" nm_Walk(10, LeftKey, BackKey) "
" nm_Walk(14.5, BackKey) "
" nm_Walk(28, LeftKey) "
" nm_Walk(36, FwdKey) "
" nm_Walk(3, RightKey) "
" nm_Walk(4, FwdKey) "
" nm_Walk(4, LeftKey) "
" nm_Walk(27, FwdKey) "
" nm_Walk(2.25, FwdKey, LeftKey) "
" nm_Walk(90, FwdKey) "
" nm_Walk(2.25, BackKey) "
" nm_Walk(22.5, RightKey) "
" nm_Walk(2.25, FwdKey) "
)"