paths["clover"] := "
(LTrim Join`r`n
" nm_Walk(18, FwdKey) "
" nm_Walk(36, RightKey) "
" nm_Walk(4.5, BackKey) "
" nm_Walk(49.5, RightKey) "
" nm_Walk(36, FwdKey) "
" nm_Walk(2.25, BackKey) "
" nm_Walk(27, RightKey) "
" nm_Walk(2.25, FwdKey) "
)"