paths["mountain top"] := "
(LTrim Join`r`n
" nm_Walk(18, FwdKey, RightKey) "
" nm_Walk(90, FwdKey) "
" nm_Walk(36, RightKey) "
" nm_Walk(27, FwdKey) "
" nm_Walk(2.25, BackKey) "
" nm_Walk(27, RightKey) "
" nm_Walk(2.25, FwdKey) "
)"